[package]
name = "breakfast-lox"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.49", features = ["derive"] }
lalrpop-util = "0.22.2"
thiserror = "2.0.17"

[build-dependencies]
lalrpop = "0.22.2"
