use crate::ast;
use std::str::FromStr;
use super::parse_error;
use super::parse_error::NumLitParseError;
use super::parse_error::DecimalFloatingPointLiteralParseError;
use super::parse_error::HexadecimalFloatingPointLiteralParseError;
use super::parse_error::IntegerLiteralParseError;
use super::parse_error::NumberIsNotFiniteParseError;

grammar;

extern {
    type Error = parse_error::ParseError;
}

match {
    // whitespace
    r"\s+" => {},
    // line comments
    r"//[^\n]*" => {},
    // block comments
    // TODO(kostya): Support nested comments (this will require moving to a custom lexer.
    // TODO(kostya): Support comments in the AST. This will mean that (1) comments must be modelled
    // in the AST (2) a decision must be made on where to attach comments. This will be required to
    // implement a formatter.
    r"/\*[^*]*\*+([^/*][^*]*\*+)*/" => {},
    "nil" => NIL,
    "print" => PRINT_KEYWORD,
    "var" => VAR_KEYWORD,
    r"[a-zA-Z_][a-zA-Z0-9_]*" => IDENTIFIER,
    // Decimal floating constants
    r"[0-9]+\.([0-9]+)?([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+|\.[0-9]+([eE][+-]?[0-9]+)?" => DEC_FLOAT,
    // Hexadecimal floating constants
    r"0[xX][0-9a-fA-F]+\.?[0-9a-fA-F]*[pP][+-]?[0-9]+|0[xX]\.[0-9a-fA-F]+[pP][+-]?[0-9]+" => HEX_FLOAT, 
    r"[0-9]+" => INTEGER,
    r#""[ -!#-\[\]-~\\]*""# => STRING,
    _
}

NilLit : ast::NilLit = {
    NIL => ast::NilLit,
}

BoolLit : ast::BoolLit = {
    "true" => ast::BoolLit(true),
    "false" => ast::BoolLit(false),
}

// TODO(kostya): These [is_finite] checks don't actually work in practice, there should be a better
// way of doing it. 
NumLit : ast::NumLit = {
    // Floating constants per ISO/IEC 9899:1999 §6.4.4.2

    DEC_FLOAT =>? {
        let x = 
            f64::from_str(<>)
                .map_err(|source| 
                    parse_error::ParseError::NumLit(
                        NumLitParseError::DecimalFloatingPointLiteral(
                            DecimalFloatingPointLiteralParseError {
                                token : <>.into(),
                                source : source.into(),
                            })))?;
        if x.is_finite() {
            Ok(ast::NumLit(x))
        } else {
            Err(
                parse_error::ParseError::NumLit(
                    NumLitParseError::NumberIsNotFinite(
                        NumberIsNotFiniteParseError {
                            token : <>.into(),
                            })))?
        }
    },

    // Hexadecimal floating constants
    HEX_FLOAT =>? {
        let x = 
            hexf_parse::parse_hexf64(<>, false)
                .map_err(|source|
                        parse_error::ParseError::NumLit(
                            NumLitParseError::HexadecimalFloatingPointLiteral(
                                HexadecimalFloatingPointLiteralParseError {
                                    token : <>.into(),
                                    source : source.into(),
                                })))?;
        if x.is_finite() {
            Ok(ast::NumLit(x))
        } else {
            Err(
                parse_error::ParseError::NumLit(
                    NumLitParseError::NumberIsNotFinite(
                        NumberIsNotFiniteParseError {
                            token : <>.into(),
                            })))?
        }
    },

    INTEGER =>? {
        let x = 
            f64::from_str(<>)
                .map_err(|source| 
                         parse_error::ParseError::NumLit(
                            NumLitParseError::IntegerLiteral(
                                IntegerLiteralParseError {
                                    token : <>.into(),
                                    source : source.into(),
                                })))?;
        if x.is_finite() {
            Ok(ast::NumLit(x))
        } else {
            Err(
                parse_error::ParseError::NumLit(
                    NumLitParseError::NumberIsNotFinite(
                        NumberIsNotFiniteParseError {
                            token : <>.into(),
                            })))?
        }
    },
}

StrLit : ast::StrLit = {
    STRING => ast::StrLit::from_raw(<>),
}

Lit : ast::Lit = {
    NilLit => ast::Lit::Nil(<>),
    BoolLit => ast::Lit::Bool(<>),
    NumLit => ast::Lit::Num(<>),
    StrLit => ast::Lit::Str(<>),
}

VarName : ast::VarName = {
    IDENTIFIER => ast::VarName(<>.into()),
}

UnOp : ast::UnOp = {
    "-" => ast::UnOp::Neg,
    "!" => ast::UnOp::Not,
}

EqOp : ast::EqOp = {
    "==" => ast::EqOp::Eq,
    "!=" => ast::EqOp::Ne,
}

CmpOp : ast::CmpOp = {
    "<" => ast::CmpOp::Lt,
    "<=" => ast::CmpOp::Le,
    ">" => ast::CmpOp::Gt,
    ">=" => ast::CmpOp::Ge,
}

AddOp : ast::AddOp = {
    "+" => ast::AddOp::Add,
    "-" => ast::AddOp::Sub,
}

MulOp : ast::MulOp = {
    "*" => ast::MulOp::Mul,
    "/" => ast::MulOp::Div,
}

pub Expr : ast::Expr = {
    EqExpr => <>
}

EqExpr : ast::Expr = {
    <l:EqExpr> <op:EqOp> <r:CmpExpr> => ast::Expr::Bin(ast::BinExpr { op : ast::BinOp::Rel(ast::RelOp::Eq(op)), l : Box::new(l), r : Box::new(r) }),
    CmpExpr 
}

CmpExpr : ast::Expr = {
    <l:TermExpr> <op:CmpOp> <r:CmpExpr> => ast::Expr::Bin(ast::BinExpr { op : ast::BinOp::Rel(ast::RelOp::Cmp(op)), l : Box::new(l), r : Box::new(r) }),
    TermExpr 
}

TermExpr : ast::Expr = {
    <l:FactorExpr> <op:AddOp> <r:TermExpr> => ast::Expr::Bin(ast::BinExpr { op : ast::BinOp::Add(op), l : Box::new(l), r : Box::new(r) }),
    FactorExpr 
}

FactorExpr : ast::Expr = {
    <l:UnExpr> <op:MulOp> <r:FactorExpr> => ast::Expr::Bin(ast::BinExpr { op : ast::BinOp::Mul(op), l : Box::new(l), r : Box::new(r) }),
    UnExpr
}

UnExpr : ast::Expr = {
    <op:UnOp> <e:UnExpr> => ast::Expr::Un(ast::UnExpr { op, e : Box::new(e) }),
    PrimExpr,
}

PrimExpr : ast::Expr = {
    Lit => ast::Expr::Lit(<>),
    VarName => ast::Expr::Var(<>),
    "(" <Expr> ")" => <>
}

pub Prog : ast::Prog = {
    DeclStmt* => ast::Prog(<>),
}

Stmt : ast::Stmt = {
    ExprStmt => ast::Stmt::Expr(<>),
    PrintStmt => ast::Stmt::Print(<>),
}

VarDecl : ast::VarDecl = {
    VAR_KEYWORD <name:VarName> <init:("=" <Expr>)?> ";" => ast::VarDecl { name , init },
}

DeclStmt : ast::Stmt = {
    VarDecl => ast::Stmt::VarDecl(<>),
    Stmt => <>
}

ExprStmt : ast::ExprStmt = {
    <Expr> ";" => ast::ExprStmt(<>),
}

PrintStmt : ast::PrintStmt = {
    PRINT_KEYWORD <Expr> ";" => ast::PrintStmt(<>),
}
