use crate::ast;
use std::str::FromStr;
use super::parse_error;
use super::parse_error::NumLitParseError;
use super::parse_error::DecimalFloatingPointLiteralParseError;
use super::parse_error::HexadecimalFloatingPointLiteralParseError;
use super::parse_error::IntegerLiteralParseError;
use super::parse_error::NumberIsNotFiniteParseError;

grammar;

extern {
    type Error = parse_error::ParseError;
}

pub NilLit : ast::NilLit = {
    "nil" => ast::NilLit,
}

pub BoolLit : ast::BoolLit = {
    "true" => ast::BoolLit(true),
    "false" => ast::BoolLit(false),
}

pub NumLit : ast::NumLit = {
    // Floating constants per ISO/IEC 9899:1999 §6.4.4.2

    // Decimal floating constants
    r"[0-9]+\.([0-9]+)?([eE][+-]?[0-9]+)?" =>? {
        let x = 
            f64::from_str(<>)
                .map_err(|source| 
                    parse_error::ParseError::NumLit(
                        NumLitParseError::DecimalFloatingPointLiteral(
                            DecimalFloatingPointLiteralParseError {
                                token : <>.to_owned(),
                                source : source.into(),
                            })))?;
        if x.is_finite() {
            Ok(ast::NumLit(x))
        } else {
            Err(
                parse_error::ParseError::NumLit(
                    NumLitParseError::NumberIsNotFinite(
                        NumberIsNotFiniteParseError {
                            token : <>.to_owned(),
                            })))?
        }
    },
    r"[0-9]+[eE][+-]?[0-9]+" =>? {
        let x = 
            f64::from_str(<>)
                .map_err(|source| 
                    parse_error::ParseError::NumLit(
                        NumLitParseError::DecimalFloatingPointLiteral(
                            DecimalFloatingPointLiteralParseError {
                                token : <>.to_owned(),
                                source : source.into(),
                            })))?;
        if x.is_finite() {
            Ok(ast::NumLit(x))
        } else {
            Err(
                parse_error::ParseError::NumLit(
                    NumLitParseError::NumberIsNotFinite(
                        NumberIsNotFiniteParseError {
                            token : <>.to_owned(),
                            })))?
        }
    },
    r"\.[0-9]+([eE][+-]?[0-9]+)?" =>? {
        let x = 
            f64::from_str(<>)
                .map_err(|source| 
                    parse_error::ParseError::NumLit(
                        NumLitParseError::DecimalFloatingPointLiteral(
                            DecimalFloatingPointLiteralParseError {
                                token : <>.to_owned(),
                                source : source.into(),
                            })))?;
        if x.is_finite() {
            Ok(ast::NumLit(x))
        } else {
            Err(
                parse_error::ParseError::NumLit(
                    NumLitParseError::NumberIsNotFinite(
                        NumberIsNotFiniteParseError {
                            token : <>.to_owned(),
                            })))?
        }
    },

    // Hexadecimal floating constants
    r"0[xX][0-9a-fA-F]+\.?[0-9a-fA-F]*[pP][+-]?[0-9]+" =>? {
        let x = 
            f64::from_str(<>)
                .map_err(|source|
                        parse_error::ParseError::NumLit(
                            NumLitParseError::HexadecimalFloatingPointLiteral(
                                HexadecimalFloatingPointLiteralParseError {
                                    token : <>.to_owned(),
                                    source : source.into(),
                                })))?;
        if x.is_finite() {
            Ok(ast::NumLit(x))
        } else {
            Err(
                parse_error::ParseError::NumLit(
                    NumLitParseError::NumberIsNotFinite(
                        NumberIsNotFiniteParseError {
                            token : <>.to_owned(),
                            })))?
        }
    },
    r"0[xX]\.[0-9a-fA-F]+[pP][+-]?[0-9]+" =>? {
        let x = 
            f64::from_str(<>)
                .map_err(|source|
                        parse_error::ParseError::NumLit(
                            NumLitParseError::HexadecimalFloatingPointLiteral(
                                HexadecimalFloatingPointLiteralParseError {
                                    token : <>.to_owned(),
                                    source : source.into(),
                                })))?;
        if x.is_finite() {
            Ok(ast::NumLit(x))
        } else {
            Err(
                parse_error::ParseError::NumLit(
                    NumLitParseError::NumberIsNotFinite(
                        NumberIsNotFiniteParseError {
                            token : <>.to_owned(),
                            })))?
        }
    },

    r"[0-9]+" =>? {
        let x = 
            f64::from_str(<>)
                .map_err(|source| 
                         parse_error::ParseError::NumLit(
                            NumLitParseError::IntegerLiteral(
                                IntegerLiteralParseError {
                                    token : <>.to_owned(),
                                    source : source.into(),
                                })))?;
        if x.is_finite() {
            Ok(ast::NumLit(x))
        } else {
            Err(
                parse_error::ParseError::NumLit(
                    NumLitParseError::NumberIsNotFinite(
                        NumberIsNotFiniteParseError {
                            token : <>.to_owned(),
                            })))?
        }
    },
}

pub StrLit : ast::StrLit = {
    r#""[ -!#-\[\]-~\\]*""# => ast::StrLit::from_raw(<>),
}

pub Lit : ast::Lit = {
    NilLit => ast::Lit::Nil(<>),
    BoolLit => ast::Lit::Bool(<>),
    NumLit => ast::Lit::Num(<>),
    StrLit => ast::Lit::Str(<>),
}

pub UnOp : ast::UnOp = {
    "-" => ast::UnOp::Neg,
    "!" => ast::UnOp::Not,
}

pub EqOp : ast::EqOp = {
    "==" => ast::EqOp::Eq,
    "!=" => ast::EqOp::Ne,
}

pub CmpOp : ast::CmpOp = {
    "<" => ast::CmpOp::Lt,
    "<=" => ast::CmpOp::Le,
    ">" => ast::CmpOp::Gt,
    ">=" => ast::CmpOp::Ge,
}

pub AddOp : ast::AddOp = {
    "+" => ast::AddOp::Add,
    "-" => ast::AddOp::Sub,
}

pub MulOp : ast::MulOp = {
    "*" => ast::MulOp::Mul,
    "/" => ast::MulOp::Div,
}

pub Expr : ast::Expr = {
    EqExpr => <>
}

pub EqExpr : ast::Expr = {
    <l:EqExpr> <op:EqOp> <r:CmpExpr> => ast::Expr::Bin(ast::BinExpr { op : ast::BinOp::Rel(ast::RelOp::Eq(op)), l : Box::new(l), r : Box::new(r) }),
    CmpExpr 
}

pub CmpExpr : ast::Expr = {
    <l:TermExpr> <op:CmpOp> <r:CmpExpr> => ast::Expr::Bin(ast::BinExpr { op : ast::BinOp::Rel(ast::RelOp::Cmp(op)), l : Box::new(l), r : Box::new(r) }),
    TermExpr 
}

pub TermExpr : ast::Expr = {
    <l:FactorExpr> <op:AddOp> <r:TermExpr> => ast::Expr::Bin(ast::BinExpr { op : ast::BinOp::Add(op), l : Box::new(l), r : Box::new(r) }),
    FactorExpr 
}

pub FactorExpr : ast::Expr = {
    <l:UnExpr> <op:MulOp> <r:FactorExpr> => ast::Expr::Bin(ast::BinExpr { op : ast::BinOp::Mul(op), l : Box::new(l), r : Box::new(r) }),
    UnExpr
}

pub UnExpr : ast::Expr = {
    <op:UnOp> <e:UnExpr> => ast::Expr::Un(ast::UnExpr { op, e : Box::new(e) }),
    PrimExpr,
}

pub PrimExpr : ast::Expr = {
    Lit => ast::Expr::Lit(<>),
    "(" <Expr> ")" => <>
}
